spring.application.name=api-andenes

server.port=8083
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.datasource.url=jdbc:postgresql://localhost:5432/navium_db?currentSchema=navium
spring.datasource.username=postgres
spring.datasource.password=Password

spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

logging.level.root=INFO
