spring.datasource.url=jdbc:postgresql://localhost:5432/navium_db
spring.datasource.username=postgres
spring.datasource.password=contrasena

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

logging.level.root=INFO

jwt.secret=NaviumSuperSecretKeyParaFirmaDeTokens2026!